// Word lists selectable on the setup screen. Within a list no categories are
// shown in-game — each flat list keeps the imposter from getting any hint
// about the word's theme.

// Easy, concrete English words.
const CLASSIC_WORDS = [
  "spoon", "fork", "knife", "plate", "cup", "bottle", "bowl", "pan", "kettle", "toaster",
  "fridge", "oven", "sink", "table", "chair", "sofa", "bed", "pillow", "blanket", "lamp",
  "door", "window", "key", "lock", "clock", "mirror", "carpet", "curtain", "shelf", "drawer",
  "dog", "cat", "horse", "cow", "pig", "sheep", "goat", "chicken", "duck", "rabbit",
  "mouse", "elephant", "lion", "tiger", "bear", "monkey", "giraffe", "zebra", "wolf", "fox",
  "deer", "owl", "eagle", "penguin", "dolphin", "whale", "shark", "octopus", "crab", "frog",
  "snake", "spider", "bee", "butterfly", "ant", "snail", "fish", "bird", "camel", "kangaroo",
  "apple", "banana", "orange", "grape", "lemon", "cherry", "peach", "pear", "melon", "strawberry",
  "pineapple", "coconut", "tomato", "potato", "carrot", "onion", "garlic", "mushroom", "corn", "pumpkin",
  "bread", "cheese", "butter", "egg", "milk", "yogurt", "honey", "sugar", "salt", "pepper",
  "rice", "pasta", "pizza", "burger", "sandwich", "soup", "salad", "cake", "cookie", "chocolate",
  "candy", "popcorn", "pancake", "waffle", "donut", "pie", "toast", "bacon", "sausage", "steak",
  "coffee", "tea", "juice", "water", "soda", "lemonade",
  "shirt", "pants", "dress", "skirt", "jacket", "coat", "sweater", "sock", "shoe", "boot",
  "hat", "cap", "scarf", "glove", "belt", "tie", "pocket", "button", "zipper", "umbrella",
  "glasses", "watch", "ring", "necklace", "wallet", "purse", "backpack",
  "car", "bus", "train", "truck", "bicycle", "motorcycle", "boat", "ship", "airplane", "helicopter",
  "rocket", "submarine", "taxi", "ambulance", "tractor", "skateboard", "scooter", "wheel", "engine", "anchor",
  "road", "bridge", "tunnel", "lighthouse", "ticket", "airport", "harbor",
  "sun", "moon", "star", "cloud", "rain", "snow", "wind", "storm", "rainbow", "lightning",
  "fire", "ice", "mountain", "hill", "valley", "river", "lake", "ocean", "beach", "island",
  "forest", "desert", "cave", "volcano", "waterfall", "field", "garden", "tree", "flower", "grass",
  "leaf", "rock", "sand", "mud", "wave", "shadow",
  "doctor", "nurse", "teacher", "student", "farmer", "chef", "pilot", "soldier", "detective", "firefighter",
  "dentist", "singer", "dancer", "actor", "painter", "writer", "judge", "king", "queen", "clown",
  "pirate", "wizard", "ghost", "robot", "astronaut", "mermaid", "vampire", "giant", "baby", "twin",
  "school", "hospital", "library", "museum", "church", "castle", "farm", "zoo", "circus", "park",
  "playground", "cinema", "restaurant", "hotel", "bank", "market", "bakery", "prison", "stadium", "gym",
  "office", "factory", "kitchen", "bathroom", "bedroom", "garage", "attic", "basement", "balcony", "roof",
  "ball", "balloon", "kite", "doll", "puzzle", "dice", "card", "drum", "guitar", "piano",
  "violin", "trumpet", "flute", "whistle", "bell", "camera", "television", "radio", "telephone", "computer",
  "book", "pencil", "pen", "paper", "scissors", "glue", "brush", "paint", "crayon", "chalk",
  "map", "flag", "coin", "stamp", "letter", "gift", "candle", "ladder", "rope", "hammer",
  "nail", "saw", "shovel", "bucket", "broom", "soap", "towel", "toothbrush", "comb", "sponge",
  "swimming", "running", "dancing", "singing", "fishing", "camping", "cooking", "painting", "reading", "sleeping",
  "football", "basketball", "tennis", "golf", "boxing", "skiing", "surfing", "bowling", "chess", "hockey",
  "birthday", "wedding", "picnic", "parade", "vacation", "morning", "night", "winter", "summer", "breakfast",
  "checkup", "haircut", "homework", "shower", "dream", "sneeze", "hiccup", "yawn", "whisper", "laugh",
  "hug", "kiss", "handshake", "clap", "wink", "smile",
  "tooth", "hair", "hand", "foot", "eye", "ear", "nose", "mouth", "heart", "brain",
  "bone", "muscle", "finger", "thumb", "knee", "elbow", "beard", "mustache", "freckle", "dimple",
];

// People from school.
const SCHOOL_WORDS = [
  "Emma Aitchison", "Benjamin Allen", "Ben Allum", "Esme Amado", "Sasha Anderson",
  "Tom Arnold", "Luke Ashley", "Josh Ayres", "Oscar Baker", "Elodie Barker",
  "Molly Barlow", "Heidi Batchelor-Hannaby", "Phoebe Bax", "Megan Baxter", "Zainab Begum",
  "Emily Bell", "Emma Blogg", "Eliza Bohn", "Ayla Bowles", "Oli Brandwood",
  "Eve Brigginshaw", "Noah Brine", "Theo Britton", "Oli Broadwith", "Alice Brooks",
  "Rose Brown-Cutler", "Alice Bugg", "Holly Bunn", "Teddy Carroll", "Margherita Castello",
  "Jack Champion", "Hari Chisholm", "Minnie Chongram", "Elliott Clarke", "Emilia Coakley",
  "Dan Connor", "Olly Cooley", "Max Cooper", "Sophie Crawley", "Holly Crowther",
  "Ellie Davis", "Alex Deciov", "Finn Delaney", "Keeva Dell", "Will Doran",
  "Talia Dorras", "Oscar Dowley", "Darcy Drew", "Milly Driver", "Luca Dujardin",
  "Gene Dunford", "Sophie-Lauren Dunn", "Fynn Dzivenu", "Robert Elderfield", "Chloe Elliot",
  "Harriet Eveson", "Nell Farquhar", "Nuala Farquharson", "Tilly Firth", "Alice Flanders",
  "Riley Florido", "Olivia Furmston", "William Gaherty", "Joe Galvin", "Ashish Ganatra",
  "Ayush Ganatra", "Layla Gardener", "Eva Garner", "Sofia Gibilaro", "Anwen Griffiths",
  "Woody Hagan", "George Halsey", "Leyla Harley", "Ollie Harris", "Matilda Harrison",
  "Paige Harrison", "Eliza Hay", "Aurek Hayes", "Louisa Herbert", "Florence Hine",
  "Harry Hine", "Jonny Hopkins", "Holly Horsfield", "Daniel Horton", "Elodie Hyatt",
  "Daniel Hyland", "Ben James", "Sam James", "Oriana Jarvis", "Cerys John",
  "Jennifer Jones", "NiNi Kempe", "Emma Kilcoyne", "Noah Kingston", "Reece Lambley-Webb",
  "Ieuan Lea", "Izzy Legge", "Evelyn Liddle", "Elsie Lindop", "Martha Lines",
  "Elina Lopez", "Eleanor Ludlow", "Edward Mancey-Jones", "Amelia Martell", "Olivia Martell",
  "Zack Martin", "James McGinley", "Fred McQueen", "Harper Melbourne", "Daniel Messulam",
  "Rose Moloney", "Nimrah Munir", "Sian Murison", "Harry Musker", "Morsal Mutaheri",
  "Ava Nation", "Jude Newman", "Ariba Niazi", "Heidie Oliver", "Sam Oruci",
  "Mel Pacitti", "Ella Page", "Maria Palfi", "Issy Parr", "Arin Parry",
  "Darshan Patel", "Nathaniel Payne", "Charlotte Perks", "Woody Pinnock", "Tilly Plenderleith",
  "Emily Price", "Emilia Quezada", "Mollie Rees", "Jack Rhodes", "Matilda Richards",
  "Isobel Roberts", "Douglas Robertson", "Millie Robson", "Jacob Rogers", "Evie Rothery",
  "Rosa Rutherfurd", "Robin Sales", "Emilia Salway", "Amelie Saunders", "Imogen Scoot",
  "Ben Silverwood-Cope", "Molly Simpson", "Arthur Size", "Ben Smith", "Ridley Sorrill",
  "Hector Spiers", "Aonghus Standen", "Sadie Stent", "Eliott Stewart", "Mollie Stewart",
  "Hannah Stout", "Gemma Sult", "Anna Teslia", "Harriet Thompson", "Isla Titheridge",
  "Evie Todd", "Sarah Trolley", "Olive Troughton", "Ellie Turner", "Alana Van Deventer",
  "Ruby Van Duyvenbode", "George Venn", "Izzy Venner", "Hugo Verstringhe", "Elodee Walker",
  "Daniel Walter", "Edward Watson", "Freddie Watson", "Tilly Weare", "Ffion Webster",
  "Lily Welbourn", "Ella Wiggs", "Josh Williams", "Izak Wilson", "Joel Winder",
  "Henry Yarker", "Daisy Yeoman", "Katie Young", "Ellie Zimet",
];

const WORD_LISTS = {
  classic: { label: "Classic", words: CLASSIC_WORDS },
  school: { label: "School", words: SCHOOL_WORDS },
};
