// Easy, concrete English words. No categories are shown in-game — this flat
// list keeps the imposter from getting any hint about the word's theme.
const WORDS = [
  "spoon", "fork", "knife", "plate", "cup", "bottle", "bowl", "pan", "kettle", "toaster",
  "fridge", "oven", "sink", "table", "chair", "sofa", "bed", "pillow", "blanket", "lamp",
  "door", "window", "key", "lock", "clock", "mirror", "carpet", "curtain", "shelf", "drawer",
  "dog", "cat", "horse", "cow", "pig", "sheep", "goat", "chicken", "duck", "rabbit",
  "mouse", "elephant", "lion", "tiger", "bear", "monkey", "giraffe", "zebra", "wolf", "fox",
  "deer", "owl", "eagle", "penguin", "dolphin", "whale", "shark", "octopus", "crab", "frog",
  "snake", "spider", "bee", "butterfly", "ant", "snail", "fish", "bird", "camel", "kangaroo",
  "apple", "banana", "orange", "grape", "lemon", "cherry", "peach", "pear", "melon", "strawberry",
  "pineapple", "coconut", "tomato", "potato", "carrot", "onion", "garlic", "mushroom", "corn", "pumpkin",
  "bread", "cheese", "butter", "egg", "milk", "yogurt", "honey", "sugar", "salt", "pepper",
  "rice", "pasta", "pizza", "burger", "sandwich", "soup", "salad", "cake", "cookie", "chocolate",
  "candy", "popcorn", "pancake", "waffle", "donut", "pie", "toast", "bacon", "sausage", "steak",
  "coffee", "tea", "juice", "water", "soda", "lemonade",
  "shirt", "pants", "dress", "skirt", "jacket", "coat", "sweater", "sock", "shoe", "boot",
  "hat", "cap", "scarf", "glove", "belt", "tie", "pocket", "button", "zipper", "umbrella",
  "glasses", "watch", "ring", "necklace", "wallet", "purse", "backpack",
  "car", "bus", "train", "truck", "bicycle", "motorcycle", "boat", "ship", "airplane", "helicopter",
  "rocket", "submarine", "taxi", "ambulance", "tractor", "skateboard", "scooter", "wheel", "engine", "anchor",
  "road", "bridge", "tunnel", "lighthouse", "ticket", "airport", "harbor",
  "sun", "moon", "star", "cloud", "rain", "snow", "wind", "storm", "rainbow", "lightning",
  "fire", "ice", "mountain", "hill", "valley", "river", "lake", "ocean", "beach", "island",
  "forest", "desert", "cave", "volcano", "waterfall", "field", "garden", "tree", "flower", "grass",
  "leaf", "rock", "sand", "mud", "wave", "shadow",
  "doctor", "nurse", "teacher", "student", "farmer", "chef", "pilot", "soldier", "detective", "firefighter",
  "dentist", "singer", "dancer", "actor", "painter", "writer", "judge", "king", "queen", "clown",
  "pirate", "wizard", "ghost", "robot", "astronaut", "mermaid", "vampire", "giant", "baby", "twin",
  "school", "hospital", "library", "museum", "church", "castle", "farm", "zoo", "circus", "park",
  "playground", "cinema", "restaurant", "hotel", "bank", "market", "bakery", "prison", "stadium", "gym",
  "office", "factory", "kitchen", "bathroom", "bedroom", "garage", "attic", "basement", "balcony", "roof",
  "ball", "balloon", "kite", "doll", "puzzle", "dice", "card", "drum", "guitar", "piano",
  "violin", "trumpet", "flute", "whistle", "bell", "camera", "television", "radio", "telephone", "computer",
  "book", "pencil", "pen", "paper", "scissors", "glue", "brush", "paint", "crayon", "chalk",
  "map", "flag", "coin", "stamp", "letter", "gift", "candle", "ladder", "rope", "hammer",
  "nail", "saw", "shovel", "bucket", "broom", "soap", "towel", "toothbrush", "comb", "sponge",
  "swimming", "running", "dancing", "singing", "fishing", "camping", "cooking", "painting", "reading", "sleeping",
  "football", "basketball", "tennis", "golf", "boxing", "skiing", "surfing", "bowling", "chess", "hockey",
  "birthday", "wedding", "picnic", "parade", "vacation", "morning", "night", "winter", "summer", "breakfast",
  "checkup", "haircut", "homework", "shower", "dream", "sneeze", "hiccup", "yawn", "whisper", "laugh",
  "hug", "kiss", "handshake", "clap", "wink", "smile",
  "tooth", "hair", "hand", "foot", "eye", "ear", "nose", "mouth", "heart", "brain",
  "bone", "muscle", "finger", "thumb", "knee", "elbow", "beard", "mustache", "freckle", "dimple",
];
